# Generated by Django 6.0.7 on 2026-07-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfile',
            old_name='name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='projectfile',
            old_name='file',
            new_name='file_path',
        ),
    ]
