# Generated by Django 6.0.7 on 2026-07-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_rename_name_projectfile_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfile',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='projectfile',
            old_name='file_name',
            new_name='name',
        ),
    ]
