# Generated by Django 6.0.7 on 2026-07-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_task_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
            ],
            options={
                'verbose_name': 'SubTask',
                'verbose_name_plural': 'SubTasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('new_app.task',),
        ),
    ]
